# #####################################################################
# Automatically generated by qmake (2.01a) lun mag 19 18:38:13 2008
# #####################################################################
TEMPLATE = lib
TARGET = zebra

#prevent linking error on some system (like ubuntu)
QMAKE_LFLAGS = -Wl,-rpath,$$[QT_INSTALL_LIBS] $$[QMAKE_LFLAGS_SHLIB]

DEPENDPATH += .
DESTDIR = ../../../bin/plugins

MOC_DIR = build/moc
RCC_DIR = build/rcc
UI_DIR = build/ui
OBJECTS_DIR = build/obj

INCLUDEPATH += . \
    ../../plugin_framework \
    ../../core

RESOURCES = resources/resources.qrc

# Input
HEADERS += PluginZebra.h \
    ../../plugin_framework/PluginProxy.h

SOURCES += PluginZebra.cpp \
    ../../plugin_framework/PluginProxy.cpp \
    ../../core/VirtualMachine.cpp \
    ../../core/HardwareInterface.cpp \
    ../../core/CollisionDomain.cpp \
    ../../plugin_framework/PluginProperty.cpp \
    ../../plugin_framework/PluginRegistry.cpp
