######################################################################
# Automatically generated by qmake (2.01a) dom mag 11 11:48:35 2008
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
#including also the PluginInterface.h
INCLUDEPATH += . ../..



# Input
HEADERS += Plugin2.h
SOURCES += Plugin2.cpp
