######################################################################
# Automatically generated by qmake (2.01a) lun mag 19 18:38:13 2008
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .

DESTDIR = ../../../bin/plugins

# including also the PluginInterface.h
INCLUDEPATH += . \
    ../../plugin_framework

RESOURCES = resources/resources.qrc

# Input
HEADERS += Plugin.h
SOURCES += Plugin.cpp \
	../../plugin_framework/PluginProxy.cpp
