######################################################################
# Automatically generated by qmake (2.01a) dom mag 11 14:48:33 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
HEADERS += PluginInterface.h

