# #####################################################################
# Automatically generated by qmake (2.01a) gio mag 22 22:03:32 2008
# #####################################################################
TEMPLATE = lib
TARGET = mac

#prevent linking error on some system (like ubuntu)
QMAKE_LFLAGS = -Wl,-rpath,$$[QT_INSTALL_LIBS] $$[QMAKE_LFLAGS_SHLIB]

DEPENDPATH += .
DESTDIR = ../../../bin/plugins

VERSION = 1.1

#QtXml is used by property expert to parse plugin xml config file
QT += xml

MOC_DIR = build/moc
RCC_DIR = build/rcc
UI_DIR = build/ui
OBJECTS_DIR = build/obj

INCLUDEPATH += . \
    ../../plugin_framework \
    ../../core
    
RESOURCES = resources/resources.qrc

# Input
HEADERS += PluginMac.h \
    ../../plugin_framework/PluginProxy.h

SOURCES += PluginMac.cpp \
    ../../plugin_framework/PluginProxy.cpp \
    ../../core/VirtualMachine.cpp \
    ../../core/HardwareInterface.cpp \
    ../../core/CollisionDomain.cpp \
    ../../plugin_framework/PluginProperty.cpp \
    ../../plugin_framework/PluginRegistry.cpp \
    ../../plugin_framework/PropertyExpert.cpp
