######################################################################
# Automatically generated by qmake (2.01a) gio mag 22 22:03:32 2008
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .

DESTDIR = ../../../bin/plugins

# including also the PluginInterface.h
INCLUDEPATH += . \
    ../../plugin_framework \
    ../../core \
    ../../gui/handles \
    ../../gui

RESOURCES = resources/resources.qrc

# Input
HEADERS += PluginIPv4.h

SOURCES += PluginIPv4.cpp \
	../../plugin_framework/PluginProxy.cpp \
	../../core/VirtualMachine.cpp \
	../../core/HardwareInterface.cpp \
	../../core/CollisionDomain.cpp \
	../../plugin_framework/PluginProperty.cpp \
	../../plugin_framework/PluginRegistry.cpp 
