# #####################################################################
# Automatically generated by qmake (2.01a) gio mag 22 22:03:32 2008
# #####################################################################
TEMPLATE = lib
TARGET = ipv4

#prevent linking error on some system (like ubuntu)
QMAKE_LFLAGS = -Wl,-rpath,$$[QT_INSTALL_LIBS] $$[QMAKE_LFLAGS_SHLIB]

DEPENDPATH += .
DESTDIR = ../../../bin/plugins

MOC_DIR = build/moc
RCC_DIR = build/rcc
UI_DIR = build/ui
OBJECTS_DIR = build/obj

VERSION = 1.1

QT += network
QT += xml

INCLUDEPATH += . \
    ../../plugin_framework \
    ../../core
    
RESOURCES = resources/resources.qrc

# Input
HEADERS += NetworkAddress.h \
    PluginIPv4.h \
    ../../plugin_framework/PluginProxy.h

SOURCES += NetworkAddress.cpp \
    PluginIPv4.cpp \
    ../../plugin_framework/PluginProxy.cpp \
    ../../core/VirtualMachine.cpp \
    ../../core/HardwareInterface.cpp \
    ../../core/CollisionDomain.cpp \
    ../../plugin_framework/PluginProperty.cpp \
    ../../plugin_framework/PluginRegistry.cpp \
    ../../plugin_framework/PropertyExpert.cpp
